// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4y5kiWuIAPdR-19PEd-wxFaguYnqGpDk',
    appId: '1:413054625629:web:e15912ed367137fc4aeab4',
    messagingSenderId: '413054625629',
    projectId: 'emoff-e82a4',
    authDomain: 'emoff-e82a4.firebaseapp.com',
    storageBucket: 'emoff-e82a4.firebasestorage.app',
    measurementId: 'G-W2EJC15ZVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9WpvP4aBrH8xcEjlSJGwEkyqg23_2wY',
    appId: '1:413054625629:android:80e6aafb392dc7c84aeab4',
    messagingSenderId: '413054625629',
    projectId: 'emoff-e82a4',
    storageBucket: 'emoff-e82a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPI8J7VCclU-HELTieZ48GSFFbvZbCAag',
    appId: '1:413054625629:ios:ee53d6ede218cede4aeab4',
    messagingSenderId: '413054625629',
    projectId: 'emoff-e82a4',
    storageBucket: 'emoff-e82a4.firebasestorage.app',
    iosBundleId: 'com.example.emoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPI8J7VCclU-HELTieZ48GSFFbvZbCAag',
    appId: '1:413054625629:ios:ee53d6ede218cede4aeab4',
    messagingSenderId: '413054625629',
    projectId: 'emoff-e82a4',
    storageBucket: 'emoff-e82a4.firebasestorage.app',
    iosBundleId: 'com.example.emoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4y5kiWuIAPdR-19PEd-wxFaguYnqGpDk',
    appId: '1:413054625629:web:f438b7b24378e9614aeab4',
    messagingSenderId: '413054625629',
    projectId: 'emoff-e82a4',
    authDomain: 'emoff-e82a4.firebaseapp.com',
    storageBucket: 'emoff-e82a4.firebasestorage.app',
    measurementId: 'G-PX9HYCGX0Z',
  );
}
